#!/bin/bash

for i in $(seq 1 10); do
  cp /etc/mcollective/server.cfg /etc/mcollective/server.$i.cfg
  echo "identity = precise64-$i" >> /etc/mcollective/server.$i.cfg
  /usr/bin/ruby /usr/sbin/mcollectived --pid=/var/run/mcollectived.$i.pid --config=/etc/mcollective/server.$i.cfg
done

